/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-08-20 01:05:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  String id = (String) session.getAttribute("id");
  if (id == null) {
      response.sendRedirect(request.getContextPath() + "/sign-in");
  }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>FITCHA</title>\r\n");
      out.write("  \r\n");
      out.write("  <link href=\"https://fontmeme.com/permalink/210816/95cfd40502d9ebe4522b74e094042fcb.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" integrity=\"sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/test/css/index.css\">\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/test/js/index.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    // 로그아웃\r\n");
      out.write("    var logout = function() {\r\n");
      out.write("      var xhrpost = new XMLHttpRequest();\r\n");
      out.write("  \r\n");
      out.write("      // 통신할 방식, url, 동기 여부 설정\r\n");
      out.write("      xhrpost.open(\"POST\", \"logout\", true);\r\n");
      out.write("      // 요청\r\n");
      out.write("      xhrpost.send();\r\n");
      out.write("      // 응답\r\n");
      out.write("      xhrpost.onreadystatechange = function() {\r\n");
      out.write("        if (xhrpost.readyState == XMLHttpRequest.DONE && xhrpost.status == 200) {\r\n");
      out.write("          location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sign-in\";\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-black\">\r\n");
      out.write("  <nav id=\"navigator\" class=\"navbar navbar-expand-lg navbar-dark fixed-top\" style=\"background-color: black; height: 70px;\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand mt-1 ml-1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-movie\">\r\n");
      out.write("        <img id=\"fitcha\" alt=\"FITCHA\" style=\"height: auto; width: 100px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/fitcha.png\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse align-items-end justify-content-between\" id=\"navbarNav\" style=\"background-color : black;\">\r\n");
      out.write("        <ul class=\"navbar-nav\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-movie\">홈</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-search\">탐색하기</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/my-board\">My Page</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main_board_view\">게시판</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mcalendar\">찜 목록</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"navbar-nav\">\r\n");
      out.write("          <li><a class=\"btn\"><i class=\"far fa-bell\"></i></a></li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("              회원 정보\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">회원 정보</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">회원 수정</a></li>\r\n");
      out.write("              <li class=\"dropdown-divider\"></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"javascript:logout();\">로그아웃</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- Carausel -->\r\n");
      out.write("  <div id=\"background-image\" class=\"carousel slide carousel-fade\" style=\"position: fixed\" data-bs-ride=\"carousel\">\r\n");
      out.write("    <div class=\"carousel-inner opacity-25\">\r\n");
      out.write("      <div class=\"carousel-item active\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/login5.jpg\" class=\"d-inline w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/login6.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/login7.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/login9.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div style=\"height: 500px\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container-fluid position-absolute top-50 start-50 translate-middle\">   \r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("      <form class=\"col-4\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-search?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"GET\">\r\n");
      out.write("        <div class=\"input-group mb-4 flex-nowrap\">\r\n");
      out.write("          <div class=\"input-group flex-nowrap input-group-lg\">\r\n");
      out.write("            <span class=\"input-group-text bg-black text-light\" id=\"addon-wrapping\" style=\"border-top-left-radius: 15px; border-bottom-left-radius: 15px;\"><i class=\"fas fa-search\" type=\"submit\"></i></span>\r\n");
      out.write("            <input type=\"text\" class=\"form-control bg-black text-light\" style=\"border-top-right-radius: 15px; border-bottom-right-radius: 15px;\" placeholder=\"영화 제목\" aria-label=\"Username\" aria-describedby=\"addon-wrapping\" name=\"title\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div style=\"height: 500px\"></div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 인기 컨텐츠 -->\r\n");
      out.write("  <div class=\"contents-title mt-5 mx-5\">인기 컨텐츠</div>\r\n");
      out.write("  <div id=\"popularIndicators\" class=\"carousel slide pb-3\" data-bs-ride=\"carousel\" data-bs-interval=\"false\">\r\n");
      out.write("    <div class=\"carousel-indicators m-0\" id=\"popular-bar\"></div>\r\n");
      out.write("    <div class=\"carousel-inner px-3 py-2\" id=\"popular-contents\"></div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#popularIndicators\" data-bs-slide=\"prev\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#popularIndicators\" data-bs-slide=\"next\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 최신 -->\r\n");
      out.write("  <div class=\"contents-title mt-5 mx-5\">최신 컨텐츠</div>\r\n");
      out.write("  <div id=\"recentIndicators\" class=\"carousel slide pb-3\" data-bs-ride=\"carousel\" data-bs-interval=\"false\">\r\n");
      out.write("    <div class=\"carousel-indicators m-0\" id=\"recent-bar\"></div>\r\n");
      out.write("    <div class=\"carousel-inner px-3 py-2\" id=\"recent-contents\"></div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#recentIndicators\" data-bs-slide=\"prev\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#recentIndicators\" data-bs-slide=\"next\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 추천 -->\r\n");
      out.write("  <div class=\"contents-title mt-5 mx-5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님에게 추천하는 컨텐츠</div>\r\n");
      out.write("  <div id=\"recommendIndicators\" class=\"carousel slide pb-3\" data-bs-ride=\"carousel\" data-bs-interval=\"false\">\r\n");
      out.write("    <div class=\"carousel-indicators m-0\" id=\"recommend-bar\"></div>\r\n");
      out.write("    <div class=\"carousel-inner px-3 py-2\" id=\"recommend-contents\"></div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#recommendIndicators\" data-bs-slide=\"prev\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#recommendIndicators\" data-bs-slide=\"next\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 성별 -->\r\n");
      out.write("  <div class=\"contents-title mt-5 mx-5\">성별 추천 컨텐츠</div>\r\n");
      out.write("  <div id=\"genderIndicators\" class=\"carousel slide pb-3\" data-bs-ride=\"carousel\" data-bs-interval=\"false\">\r\n");
      out.write("    <div class=\"carousel-indicators m-0\" id=\"gender-bar\"></div>\r\n");
      out.write("    <div class=\"carousel-inner px-3 py-2\" id=\"gender-contents\"></div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#genderIndicators\" data-bs-slide=\"prev\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#genderIndicators\" data-bs-slide=\"next\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 나이 -->\r\n");
      out.write("  <div class=\"contents-title mt-5 mx-5\">나이별 추천 컨텐츠</div>\r\n");
      out.write("  <div id=\"ageIndicators\" class=\"carousel slide pb-3\" data-bs-ride=\"carousel\" data-bs-interval=\"false\">\r\n");
      out.write("    <div class=\"carousel-indicators m-0\" id=\"age-bar\"></div>\r\n");
      out.write("    <div class=\"carousel-inner px-3 py-2\" id=\"age-contents\"></div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#ageIndicators\" data-bs-slide=\"prev\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#ageIndicators\" data-bs-slide=\"next\" style=\"width: 30px;\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 모달 -->\r\n");
      out.write("  <div class=\"modal fade show\" style=\"display: none;\" id=\"movieModal\" aria-hidden=\"false\">\r\n");
      out.write("    <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("      <div class=\"modal-content bg-dark\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h5 class=\"modal-title text-light\" id=\"movieTitle\"></h5>\r\n");
      out.write("          <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <iframe id=\"movieTrailer\" frameborder=\"0\" width=100% height='470' allowfullscreen></iframe>\r\n");
      out.write("          <div class=\"d-flex\">\r\n");
      out.write("            <img id=\"moviePoster\" alt=\"\" class=\"m-3 col-lg-3 col-6\">\r\n");
      out.write("            <p id=\"movieStory\" class=\"text-light m-3\" style=\"overflow: auto; height: 350px;\"></p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"d-flex\">\r\n");
      out.write("            <div class=\"col-3 m-3 text-light\">\r\n");
      out.write("              <p id=\"movieOpenDate\" class=\"text-light m-3\"></p>\r\n");
      out.write("              <p id=\"movieGrade\" class=\"text-light m-3\"></p>\r\n");
      out.write("              <p id=\"movieCountry\" class=\"text-light m-3\"></p>\r\n");
      out.write("              <p id=\"movieRunningTime\" class=\"text-light m-3\"></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text-light m-2 mt-3\">\r\n");
      out.write("              <p id=\"movieGenre\" class=\"text-light m-3\"></p>\r\n");
      out.write("              <p id=\"movieStaff\" class=\"text-light m-3\"></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"staffList\" class=\"d-flex\" style=\"overflow-x: scroll;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\" style=\"display: inline;\">\r\n");
      out.write("          <div class=\"row buttonList\">\r\n");
      out.write("            <div class=\"col-sm-9\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-secondary\" id=\"dipBtn\" value=\"none\" style=\"border-radius: 50%\">\r\n");
      out.write("                <i class=\"fas fa-plus text-dark\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-secondary\" id=\"likeBtn\" value=\"none\" style=\"border-radius: 50%\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up text-dark\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-3\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-secondary ms-5\" data-bs-target=\"#reviewModal\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\">리뷰 작성</button>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-light\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 리뷰 작성 모달창 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"reviewModal\" aria-hidden=\"true\" aria-labelledby=\"exampleModalToggleLabel2\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("      <div class=\"modal-content bg-dark text-light\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h5 class=\"modal-title\" id=\"exampleModalToggleLabel2\">Review</h5>\r\n");
      out.write("          <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"reviewTitle\" class=\"form-label\">TITLE</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"reviewTitle\" placeholder=\"제목\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"reviewDate\" class=\"form-label\">DATE</label>\r\n");
      out.write("            <input type=\"date\" class=\"form-control\" id=\"reviewDate\" readonly=\"readonly\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-check mb-3\">\r\n");
      out.write("            <input class=\"form-check-input\" type=\"radio\" name=\"reviewAccess\" id=\"open\" value=\"O\">\r\n");
      out.write("            <label class=\"form-check-label\" for=\"open\"> 공개 </label> <br>\r\n");
      out.write("            <input class=\"form-check-input\" type=\"radio\" name=\"reviewAccess\" id=\"close\" value=\"C\" checked>\r\n");
      out.write("            <label class=\"form-check-label\" for=\"close\"> 비공개 </label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"contents\" class=\"form-label\">내용</label>\r\n");
      out.write("            <textarea class=\"form-control\" id=\"reviewContents\" rows=\"3\" placeholder=\"내용\" required></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button class=\"btn btn-secondary\" id=\"reviewBtn\">작성</button>\r\n");
      out.write("          <button class=\"btn btn-light\" data-bs-target=\"#exampleModalToggle\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <footer class=\"text-center\">\r\n");
      out.write("    <p>&copy 2021 FITCHA, Inc.</p>\r\n");
      out.write("    <p>KITRI &copy 2021</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
