/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-08-19 17:57:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fitcha.model.vo.MainBoardVO;
import com.fitcha.model.dao.MainBoardDAO;

public final class review_002dboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.fitcha.model.vo.MainBoardVO");
    _jspx_imports_classes.add("com.fitcha.model.dao.MainBoardDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 	String userId = (String)session.getAttribute("id");
	System.out.println("userId: "+ userId);
// 	String userId = "rrr";
   if(userId==null){
	   
       response.sendRedirect(request.getContextPath() + "/sign-in");
   }
   
   String boardId = request.getParameter("boardId");
   MainBoardDAO bdao = new MainBoardDAO();
   MainBoardVO bvo = bdao.reviewDetail(boardId);

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <title>FitCha</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <!-- CSS only -->\r\n");
      out.write("  <link href=\"https://fontmeme.com/permalink/210816/95cfd40502d9ebe4522b74e094042fcb.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/board/review-board.css\" >\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" integrity=\"sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/board/review-board.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/board/comment.js\"></script>\r\n");
      out.write("  <script defer src=\"https://use.fontawesome.com/releases/v5.1.0/js/all.js\" integrity=\"sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    var userId = '");
      out.print((String)session.getAttribute("id"));
      out.write("';\r\n");
      out.write("    \r\n");
      out.write(" // 로그아웃\r\n");
      out.write("    var logout = function() {\r\n");
      out.write("      var xhrpost = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("      // 통신할 방식, url, 동기 여부 설정\r\n");
      out.write("      xhrpost.open(\"POST\", \"logout\", true);\r\n");
      out.write("      // 요청\r\n");
      out.write("      xhrpost.send();\r\n");
      out.write("      // 응답\r\n");
      out.write("      xhrpost.onreadystatechange = function() {\r\n");
      out.write("        if (xhrpost.readyState == XMLHttpRequest.DONE && xhrpost.status == 200) {\r\n");
      out.write("          location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sign-in\";\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 	 <div class=\"wrapper\"> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("<nav id=\"navigator\" class=\"navbar navbar-expand-lg navbar-dark fixed-top\" style=\"background-color: black; height: 70px;\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand mt-1 ml-1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-movie\">\r\n");
      out.write("          <img id=\"fitcha\" alt=\"FITCHA\" style=\"height: auto; width: 100px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/fitcha.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse align-items-end justify-content-between\" id=\"navbarNav\" style=\"background-color: black;\">\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-movie\">홈</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-search\">탐색하기</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/my-board\">My Page</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main_board_view\">게시판</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mcalendar\">찜 목록</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"btn\">\r\n");
      out.write("                <i class=\"far fa-bell\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> 회원 정보 </a>\r\n");
      out.write("              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">회원 정보</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">회원 수정</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown-divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"javascript:logout();\">로그아웃</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- END OF HEADER -->\r\n");
      out.write("    <div id=\"head-box\">\r\n");
      out.write("	    <h1 id=\"review-h1\">	<!-- ~님의 REVIEW (review-board.js) -->\r\n");
      out.write("	    </h1>\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    <div id=\"like-btn\">\r\n");
      out.write("		    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"like()\" style=\"border-radius: 50%\">\r\n");
      out.write("				<i class=\"fas fa-heart text-light\" ></i>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!--     <div id=\"review-box\"> -->\r\n");
      out.write("    	<div id=\"review-box\">\r\n");
      out.write("<!--    해당되는 게시물 보여주기 (review-board.js) -->\r\n");
      out.write("    	</div>\r\n");
      out.write("    ");

		if(userId != null && userId.equals(bvo.getUserId())){
						
	
      out.write("\r\n");
      out.write("    <div id=\"update-btn\">\r\n");
      out.write("		    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"updateBoard()\" style=\"border-radius: 50%\">\r\n");
      out.write("				<i class=\"fas fa-pen\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("		    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"deleteBoard()\" style=\"border-radius: 50%\">\r\n");
      out.write("				<i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 	    	<button type=\"submit\" onclick=\"updateBoard()\">수정</button> -->\r\n");
      out.write("<!-- 	    	<button type=\"submit\" onclick=\"deleteBoard()\">삭제</button> -->\r\n");
      out.write("  \r\n");
      out.write("    ");

		}
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <hr class=\"hr\">\r\n");
      out.write("    <div id=\"comments\">\r\n");
      out.write("		<div class=\"comment-row\">\r\n");
      out.write("	    	<textarea id=\"new-comment\" name=\"new_comment\" rows=2 placeholder=\"댓글을 입력해주세요.\" ></textarea>\r\n");
      out.write("	    	<button type=\"button\" class=\"btn btn-secondary\" id=\"comment-btn\" onclick=\"submitComment()\" style=\"border-radius: 50%\">\r\n");
      out.write("			    <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    <div id=\"comment-row1\">\r\n");
      out.write("	    <!-- 댓글로드 -->\r\n");
      out.write("	    </div>\r\n");
      out.write("	 </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    		<!-- FOOTER -->\r\n");
      out.write("<!--     <footer> -->\r\n");
      out.write("<!--       <p>&copy 1997-2018 FITCHA, Inc.</p> -->\r\n");
      out.write("<!--       <p>KONG &copy 2018</p> -->\r\n");
      out.write("<!--     </footer> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
