/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-08-19 18:02:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fitcha.model.vo.MainBoardVO;
import com.fitcha.controller.Pagination;
import java.util.List;
import com.fitcha.model.dao.MainBoardDAO;

public final class main_002dboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1627885080000L));
    _jspx_dependants.put("jar:file:/C:/Java/JSP/kitriproject/apache-tomcat-9.0.52-windows-x64/apache-tomcat-9.0.52/wtpwebapps/fitcha_merge/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.fitcha.controller.Pagination");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fitcha.model.vo.MainBoardVO");
    _jspx_imports_classes.add("com.fitcha.model.dao.MainBoardDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    MainBoardDAO bdao = new MainBoardDAO();
//List<BoardVO> blist = bdao.selectBoardList();

//페이징 처리 적용
String curPage = request.getParameter("curpage");
if (curPage == null) {
	curPage = "1";
}
int curPageInt = Integer.parseInt(curPage);
int totalContent = bdao.selectBoardCnt();

Pagination pagination = new Pagination(curPageInt, totalContent, 5);

//1page내에 보여줘야하는 게시물의 첫번째 rownum
int start = curPageInt * pagination.getContentCnt() - (pagination.getContentCnt() - 1);
//한페이지 내에 보여줘야하는 게시물의 마지막 rownum
int end = curPageInt * pagination.getContentCnt();

List<MainBoardVO> blist = bdao.selectBoardPage(start, end);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /WEB-INF/board/main-board.jsp(33,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("page");
        // /WEB-INF/board/main-board.jsp(33,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(pagination);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /WEB-INF/board/main-board.jsp(34,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("blist");
        // /WEB-INF/board/main-board.jsp(34,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(blist);
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>FitCha</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"https://fontmeme.com/permalink/210816/95cfd40502d9ebe4522b74e094042fcb.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" integrity=\"sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/board/main-board.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"shortcut icon\" href=\"#\"> -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/board/main-board.js\"></script>\r\n");
      out.write("<script defer src=\"https://use.fontawesome.com/releases/v5.1.0/js/all.js\" integrity=\"sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9\" crossorigin=\"anonymous\">\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  //썸네일 클릭했을때 리뷰디테일 페이지로 이동\r\n");
      out.write("  function thumbnail(boardId) {\r\n");
      out.write("    //조회수증가\r\n");
      out.write("\r\n");
      out.write("    location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/review_board_view?boardId=\"\r\n");
      out.write("        + boardId;\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  //로그아웃\r\n");
      out.write("  var logout = function() {\r\n");
      out.write("    var xhrpost = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("    // 통신할 방식, url, 동기 여부 설정\r\n");
      out.write("    xhrpost.open(\"POST\", \"logout\", true);\r\n");
      out.write("    // 요청\r\n");
      out.write("    xhrpost.send();\r\n");
      out.write("    // 응답\r\n");
      out.write("    xhrpost.onreadystatechange = function() {\r\n");
      out.write("      if (xhrpost.readyState == XMLHttpRequest.DONE && xhrpost.status == 200) {\r\n");
      out.write("        location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sign-in\";\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("    <nav id=\"navigator\" class=\"navbar navbar-expand-lg navbar-dark fixed-top\" style=\"background-color: black; height: 70px;\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand mt-1 ml-1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-movie\">\r\n");
      out.write("          <img id=\"fitcha\" alt=\"FITCHA\" style=\"height: auto; width: 100px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/fitcha.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse align-items-end justify-content-between\" id=\"navbarNav\" style=\"background-color: black;\">\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-movie\">홈</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main-search\">탐색하기</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/my-board\">My Page</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main_board_view\">게시판</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mcalendar\">찜 목록</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"btn\">\r\n");
      out.write("                <i class=\"far fa-bell\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> 회원 정보 </a>\r\n");
      out.write("              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">회원 정보</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">회원 수정</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown-divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"javascript:logout();\">로그아웃</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- END OF HEADER -->\r\n");
      out.write("\r\n");
      out.write("    <!-- --------------------------------최고 인기 리뷰와 해당 게시물 이미지 띄어주는 박스 --------------------------------------------------------------------------- -->\r\n");
      out.write("    <div style=\"height:50px;\"></div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div id=\"fixImg\">\r\n");
      out.write("        <div id=\"test\">\r\n");
      out.write("          <div id=\"best\" class=\"d-flex justify-content-between m-5\">\r\n");
      out.write("            <!-- -------------------------------최고 인기 리뷰---------------------------------------------- -->\r\n");
      out.write("            <div id=\"best-text\" class=\"col-auto .me-auto\">\r\n");
      out.write("              <h2 id=\"best-h2\">FITCHA 최고 인기 리뷰</h2>\r\n");
      out.write("              <div id=\"best-sub-text\" class=\"row\">\r\n");
      out.write("                <p id=\"best-p\" class=\"h-auto d-inline-block\">\r\n");
      out.write("                <div>어벤져스, 해리포터 등 지금 가장 많이 보는 작품!</div>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"best-content\" class=\"row\">\r\n");
      out.write("                <p id=\"best-content-p\">\r\n");
      out.write("                  극장 최신 개봉작부터 고전 영화까지, 블록버스터 영화부터 다양성 영화까지! <br>다양한 작품들의 감상을 자유롭게 작성해주세요:)\r\n");
      out.write("                </p>\r\n");
      out.write("                <p id=\"best-content-p\">Fitcha의 가장 인기있는 리뷰를 보러 가고 싶다면 클릭!</p>\r\n");
      out.write("                <div class=\"align-self-end\">\r\n");
      out.write("                  <p id=\"best-reviewText\" class=\"row\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"best-review\" class=\"col-auto\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--      	<p id=\"best-reviewText\" class=\"row\"> </p> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- -------------------------------------main 가장 많은 리뷰 띄어주는 부분------------------------- -->\r\n");
      out.write("        <!-- 	    ajax 비동기통신으로 좋아요가 가장 많은 리뷰를 띄워주는 부분 -->\r\n");
      out.write("        <!-- 	    	<div id=\"best-board-img\"> -->\r\n");
      out.write("        <!-- 				<img src=\"img/avenger.jpg\" alt=\"Logo Image\"> -->\r\n");
      out.write("        <!-- 			</div> -->\r\n");
      out.write("        <!-- 			<div id=\"best-writer\"> -->\r\n");
      out.write("        <!-- 				<div id=\"best-board-writer\"> -->\r\n");
      out.write("        <!-- 					<p id=\"writer-p\">작성자</p> -->\r\n");
      out.write("        <!-- 					<p id=\"writer\">kangjisoo</p> -->\r\n");
      out.write("        <!-- 				</div> -->\r\n");
      out.write("        <!-- 				<div id=\"best-board-title\"> -->\r\n");
      out.write("        <!-- 					<p id=\"title-p\">제목</p> -->\r\n");
      out.write("        <!-- 					<p id=\"title\"><a href=\"#\">어벤져스:인피니티 워 리뷰</a></p> -->\r\n");
      out.write("        <!-- 				</div> -->\r\n");
      out.write("        <!-- 			</div> -->\r\n");
      out.write("\r\n");
      out.write("        <!-- --------------------------------------------------------------------------------------- -->\r\n");
      out.write("        <!-- ----------------------------------------------------------------------------------------------------------- ---------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("        <!-- --------------------------------------review context 박스---------------------------------- -->\r\n");
      out.write("        <div id=\"best\" class=\"d-flex justify-content-start\">\r\n");
      out.write("          <div id=\"selectBox\" class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div id=\"review-p\" class=\"d-flex justify-content-start\">\r\n");
      out.write("                <h3>보고싶은 리뷰를 찾아보세요!</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ---------------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("            <!-- -------------------------------select 부분------------------------------------------------ -->\r\n");
      out.write("            <div id=\"select-box\">\r\n");
      out.write("              <select id=\"genre\" onchange=\"changeSelection()\">\r\n");
      out.write("\r\n");
      out.write("                <option value=\"0\">모든 장르</option>\r\n");
      out.write("                <option value=\"11\">코미디</option>\r\n");
      out.write("                <option value=\"1\">드라마</option>\r\n");
      out.write("                <option value=\"5\">로맨스</option>\r\n");
      out.write("                <option value=\"19\">액션</option>\r\n");
      out.write("                <option value=\"18\">SF</option>\r\n");
      out.write("                <option value=\"15\">애니메이션</option>\r\n");
      out.write("                <option value=\"4\">공포</option>\r\n");
      out.write("                <option value=\"7\">스릴러</option>\r\n");
      out.write("                <option value=\"6\">모험</option>\r\n");
      out.write("                <option value=\"2\">판타지</option>\r\n");
      out.write("                <option value=\"8\">느와르</option>\r\n");
      out.write("                <option value=\"10\">다큐멘터리</option>\r\n");
      out.write("                <option value=\"12\">가족</option>\r\n");
      out.write("                <option value=\"17\">뮤지컬</option>\r\n");
      out.write("                <option value=\"13\">미스터리</option>\r\n");
      out.write("                <option value=\"14\">전쟁</option>\r\n");
      out.write("                <option value=\"16\">범죄</option>\r\n");
      out.write("              </select>\r\n");
      out.write("              <select id=\"recommend\" onchange=\"changeSelection()\">\r\n");
      out.write("                <option value=\"1\">최신리뷰 순</option>\r\n");
      out.write("                <option value=\"2\">추천 순</option>\r\n");
      out.write("                <option value=\"3\">평균별점 순</option>\r\n");
      out.write("                <option value=\"4\">러닝타임 짧은 순</option>\r\n");
      out.write("              </select>\r\n");
      out.write("\r\n");
      out.write("              <div id=\"search-box\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"영화제목 검색\" id=\"searchBox\" name=\"searchBox\">\r\n");
      out.write("                <button type=\"button\" class=\"fa fa-search\" id=\"search_btn\" aria-hidden=\"true\" onclick=\"searchInput()\"></button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ----------------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- <-----------------------------------------------review -------------------------------------->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <h2 class=\"text-center mt-5\">REVIEW</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ------------------------------------------------------------------------------------------ -->\r\n");
      out.write("\r\n");
      out.write("    <!--  ------------------------------------생성되는 이미지(게시물) 박스란---------------------------------------------------------------------------------- -->\r\n");
      out.write("    <div>\r\n");
      out.write("      <!--       <div class=\"container\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div id=\"row\" class=\"row\">\r\n");
      out.write("        <!-- 				ajax 비동기통신을 통해 전체 게시물을 띄워주는 부분  -->\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--       </div> -->\r\n");
      out.write("\r\n");
      out.write("      <!-- 	페이지 개수 -->\r\n");
      out.write("\r\n");
      out.write("      <!-- ----------------------v페이지-------------------------------------------------- -->\r\n");
      out.write("      <!-- <div> -->\r\n");
      out.write("      <!--       <ul id=page> -->\r\n");
      out.write("\r\n");
      out.write("      <!--         			이전페이지 -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--           <li> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--           </li> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!--         			페이지 넣기 -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--               <li> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--               </li> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!--         			다음페이지 -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--           <li> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--           </li> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--       </ul> -->\r\n");
      out.write("      <!--    </div>  -->\r\n");
      out.write("      <!-- -------------------------------------------------------------------------------- -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ------------------------------------------------------------------------------------------------------------------------------------------------ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- FOOTER -->\r\n");
      out.write("    <footer class=\"text-center\">\r\n");
      out.write("      <p>&copy 2021 FITCHA, Inc.</p>\r\n");
      out.write("      <p>KITRI &copy 2021</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
